version: "3.9"

# Change MODE on all services to switch replication strategy.
# Valid values: W5R1 | W1R5 | W3R3
x-mode: &mode W3R3

services:
  leader:
    build:
      context: .
      dockerfile: leader-follower/Dockerfile
    environment:
      ROLE: leader
      MODE: *mode
      ADDR: ":8080"
      PEERS: >-
        http://follower1:8080,
        http://follower2:8080,
        http://follower3:8080,
        http://follower4:8080
    ports:
      - "8080:8080"
    networks:
      - kvnet

  follower1:
    build:
      context: .
      dockerfile: leader-follower/Dockerfile
    environment:
      ROLE: follower
      MODE: *mode
      ADDR: ":8080"
    ports:
      - "8081:8080"
    networks:
      - kvnet

  follower2:
    build:
      context: .
      dockerfile: leader-follower/Dockerfile
    environment:
      ROLE: follower
      MODE: *mode
      ADDR: ":8080"
    ports:
      - "8082:8080"
    networks:
      - kvnet

  follower3:
    build:
      context: .
      dockerfile: leader-follower/Dockerfile
    environment:
      ROLE: follower
      MODE: *mode
      ADDR: ":8080"
    ports:
      - "8083:8080"
    networks:
      - kvnet

  follower4:
    build:
      context: .
      dockerfile: leader-follower/Dockerfile
    environment:
      ROLE: follower
      MODE: *mode
      ADDR: ":8080"
    ports:
      - "8084:8080"
    networks:
      - kvnet

networks:
  kvnet:
    driver: bridge